name: Infrastructure and Deployment Pipeline

on:
  push:
    branches: [main]

env:
  AWS_REGION: 'us-west-2'
  FLASK_PORT: '5000'

jobs:
  provision-infrastructure:
    runs-on: ubuntu-latest
    outputs:
      ec2_ip: ${{ steps.get-outputs.outputs.public_ip }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        id: terraform-apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Get Terraform Outputs
        id: get-outputs
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          PUBLIC_IP=$(terraform -chdir=./terraform output -raw public_ip)
          echo "public_ip=${PUBLIC_IP}" >> $GITHUB_OUTPUT
          echo "EC2_IP=${PUBLIC_IP}" >> $GITHUB_ENV
          terraform -chdir=./terraform output -raw ssh_private_key > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Wait for Instance Readiness
        run: |
          IP=${{ env.EC2_IP }}
          until nc -z -w5 $IP 22; do sleep 10; done

  deploy-application:
    needs: provision-infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ needs.provision-infrastructure.outputs.ssh_key }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/re2pect-app:latest
            ghcr.io/${{ github.repository_owner }}/re2pect-app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy with Traefik Ingress
        run: |
          DEPLOYMENT_YAML=$(cat <<-EOF
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: re2pect-app
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: re2pect-app
            template:
              metadata:
                labels:
                  app: re2pect-app
              spec:
                containers:
                - name: app
                  image: ghcr.io/${{ github.repository_owner }}/re2pect-app:${{ github.sha }}
                  ports:
                  - containerPort: ${{ env.FLASK_PORT }}
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: re2pect-app-service
          spec:
            ports:
            - port: ${{ env.FLASK_PORT }}
              targetPort: ${{ env.FLASK_PORT }}
            selector:
              app: re2pect-app
          ---
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: re2pect-app-ingress
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: web
          spec:
            rules:
            - http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: re2pect-app-service
                      port:
                        number: ${{ env.FLASK_PORT }}
          EOF
          )
          
          ssh -i ~/.ssh/deploy_key \
              ec2-user@${{ needs.provision-infrastructure.outputs.ec2_ip }} \
              "kubectl apply -f -" <<< "$DEPLOYMENT_YAML"

      - name: Verify Deployment
        run: |
          ssh -i ~/.ssh/deploy_key \
              ec2-user@${{ needs.provision-infrastructure.outputs.ec2_ip }} \
              "kubectl get pods,svc,ingress"